spring.application.name=demo
# Configurações do Banco de Dados H2
spring.datasource.url=jdbc:h2:mem:botfaculdade
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Permite que o Spring crie as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilita uma interface visual no navegador para você ver o banco
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.defer-datasource-initialization=true
